/* eslint-disable import/prefer-default-export */
export const response = {
  data: {
    status: 'ok',
    totalResults: 10,
    articles: [{
      source: { id: 'reuters', name: 'Reuters' }, author: 'Guy Faulconbridge', title: "Brexit on a knife edge as PM Johnson stakes all on 'Super Saturday' vote", description: "Britain's exit from the European Union hung on a knife-edge on Friday as Prime Minister Boris Johnson scrambled to persuade doubters to rally behind his last-minute European Union divorce deal in an extraordinary vote in parliament.", url: 'http://feeds.reuters.com/~r/reuters/topNews/~3/2NdWCwqhNio/brexit-on-a-knife-edge-as-pm-johnson-stakes-all-on-super-saturday-vote-idUSKBN1WX0SJ', urlToImage: 'https://s2.reutersmedia.net/resources/r/?m=02&d=20191018&t=2&i=1442208568&w=1200&r=LYNXMPEF9H0LH', publishedAt: '2019-10-18T10:00:02Z', content: 'LONDON (Reuters) - Britain’s exit from the European Union hung on a knife-edge on Friday as Prime Minister Boris Johnson scrambled to persuade doubters to rally behind his last-minute European Union divorce deal in an extraordinary vote in parliament. \r\nIn on… [+4649 chars]',
    }, {
      source: { id: 'reuters', name: 'Reuters' }, author: 'Amanda Ferguson', title: "As Troubles cast long shadow, Brexit stakes are high in Northern Ireland's border city", description: "Just a few kilometers from the border with Ireland, the people of Northern Ireland's second city of Londonderry know exactly what is at stake as Britain seeks to seal its departure from the European Union.", url: 'http://feeds.reuters.com/~r/reuters/topNews/~3/YG5sfX7R6-M/as-troubles-cast-long-shadow-brexit-stakes-are-high-in-northern-irelands-border-city-idUSKBN1WX0NE', urlToImage: 'https://s1.reutersmedia.net/resources/r/?m=02&d=20191018&t=2&i=1442222950&w=1200&r=LYNXMPEF9H0Q1', publishedAt: '2019-10-18T09:56:44Z', content: 'LONDONDERRY (Reuters) - Just a few kilometers from the border with Ireland, the people of Northern Ireland’s second city of Londonderry know exactly what is at stake as Britain seeks to seal its departure from the European Union. \r\nAlmost 50 years ago, the ci… [+6275 chars]',
    }, {
      source: { id: 'reuters', name: 'Reuters' }, author: 'Marc Jones', title: 'Shares slip on weak China growth, dollar suffers weekly mauling', description: 'World stocks slipped after China posted its weakest growth rate in nearly three decades on Friday, while the dollar was set for its worst week in almost four months having been pummeled by pound and euro Brexit rallies.', url: 'http://feeds.reuters.com/~r/reuters/topNews/~3/fZbJjQPiO8Q/shares-slip-on-weak-china-growth-dollar-suffers-weekly-mauling-idUSKBN1WX03J', urlToImage: 'https://s4.reutersmedia.net/resources/r/?m=02&d=20191018&t=2&i=1442234670&w=1200&r=LYNXMPEF9H0T9', publishedAt: '2019-10-18T09:33:09Z', content: 'LONDON (Reuters) - World stocks slipped after China posted its weakest growth rate in nearly three decades on Friday, while the dollar was set for its worst week in almost four months having been pummeled by pound and euro Brexit rallies. \r\nChina’s economy gr… [+3751 chars]',
    }, {
      source: { id: 'reuters', name: 'Reuters' }, author: 'Reuters Editorial', title: 'Thousands converge on Barcelona for fifth day of Catalan protests', description: "Hundreds of thousands of pro-independence supporters from across Spain's northeastern region of Catalonia are expected to pour into Barcelona on Friday, as unions called for a general strike on the fifth day of protests following the jailing of nine separatis…", url: 'http://feeds.reuters.com/~r/reuters/topNews/~3/vsaQQl_NmIo/thousands-converge-on-barcelona-for-fifth-day-of-catalan-protests-idUSKBN1WX0TY', urlToImage: 'https://s3.reutersmedia.net/resources/r/?m=02&d=20191018&t=2&i=1442234586&w=1200&r=LYNXMPEF9H0SL', publishedAt: '2019-10-18T09:32:30Z', content: 'BARCELONA (Reuters) - Hundreds of thousands of pro-independence supporters from across Spain’s northeastern region of Catalonia are expected to pour into Barcelona on Friday, as unions called for a general strike on the fifth day of protests following the jai… [+2411 chars]',
    }, {
      source: { id: 'reuters', name: 'Reuters' }, author: 'Dave Graham', title: "Cartel gunmen terrorize Mexican city, free El Chapo's son", description: "Heavily armed fighters surrounded security forces in a Mexican city on Thursday and made them free one of drug lord Joaquin 'El Chapo' Guzman's sons, after his capture triggered gunbattles and a prison break that sent civilians scurrying for cover.", url: 'http://feeds.reuters.com/~r/reuters/topNews/~3/rxfwGijpgkY/cartel-gunmen-terrorize-mexican-city-free-el-chapos-son-idUSKBN1WW34M', urlToImage: 'https://s3.reutersmedia.net/resources/r/?m=02&d=20191018&t=2&i=1442147716&w=1200&r=LYNXMPEF9H09M', publishedAt: '2019-10-18T09:23:27Z', content: 'MEXICO CITY (Reuters) - Heavily armed fighters surrounded security forces in a Mexican city on Thursday and made them free one of drug lord Joaquin ‘El Chapo’ Guzman’s sons, after his capture triggered gunbattles and a prison break that sent civilians scurryi… [+4447 chars]',
    }, {
      source: { id: 'reuters', name: 'Reuters' }, author: 'Rami Ayyub', title: "Pompeo seeks to assure Israel-U.S focus stays on Iran 'threat'", description: 'Secretary of State Mike Pompeo underscored U.S.-Israeli efforts to counter Iran in talks with Prime Minister Benjamin Netanyahu on Friday, in an apparent attempt to ease concerns in Israel that Tehran could exploit a U.S. military pullback in Syria.', url: 'http://feeds.reuters.com/~r/reuters/topNews/~3/mFoDnerrE-I/pompeo-seeks-to-assure-israel-u-s-focus-stays-on-iran-threat-idUSKBN1WX0NO', urlToImage: 'https://s2.reutersmedia.net/resources/r/?m=02&d=20191018&t=2&i=1442228661&w=1200&r=LYNXMPEF9H0FB', publishedAt: '2019-10-18T09:13:13Z', content: 'JERUSALEM (Reuters) - Secretary of State Mike Pompeo underscored U.S.-Israeli efforts to counter Iran in talks with Prime Minister Benjamin Netanyahu on Friday, in an apparent attempt to ease concerns in Israel that Tehran could exploit a U.S. military pullba… [+3415 chars]',
    }, {
      source: { id: 'reuters', name: 'Reuters' }, author: 'Reuters Editorial', title: "Lebanon's PM cancels cabinet meeting: Al Manar TV citing minister", description: "Lebanon's Prime Minister Saad al-Hariri has canceled a cabinet meeting scheduled for Friday amid nationwide protests, Al Manar TV quoted the interior minister as saying.", url: 'http://feeds.reuters.com/~r/reuters/topNews/~3/127TKtOmCog/lebanons-pm-cancels-cabinet-meeting-al-manar-tv-citing-minister-idUSKBN1WX0ZG', urlToImage: 'https://s2.reutersmedia.net/resources/r/?m=02&d=20191018&t=2&i=1442225878&w=1200&r=LYNXMPEF9H0R4', publishedAt: '2019-10-18T09:02:36Z', content: 'BEIRUT (Reuters) - Lebanon’s Prime Minister Saad al-Hariri has canceled a cabinet meeting scheduled for Friday amid nationwide protests, Al Manar TV quoted the interior minister as saying. \r\nThe anti-government protests in a country mired in economic crisis e… [+91 chars]',
    }, {
      source: { id: 'reuters', name: 'Reuters' }, author: 'Frank Pingue', title: "NBA's Silver says Hong Kong tweet furor already hit league's bottom line", description: 'NBA Commissioner Adam Silver said on Thursday that the fallout following a tweet from a Houston Rockets official who backed the Hong Kong democracy protests has already cost the league substantial financial losses in China.', url: 'http://feeds.reuters.com/~r/reuters/topNews/~3/rAxnhH8Ir-s/nbas-silver-says-hong-kong-tweet-furor-already-hit-leagues-bottom-line-idUSKBN1WW32B', urlToImage: 'https://s3.reutersmedia.net/resources/r/?m=02&d=20191018&t=2&i=1442205432&w=1200&r=LYNXMPEF9G297', publishedAt: '2019-10-18T09:00:26Z', content: '(Reuters) - NBA Commissioner Adam Silver said on Thursday that the fallout following a tweet from a Houston Rockets official who backed the Hong Kong democracy protests has already cost the league substantial financial losses in China. \r\nThe National Basketba… [+2094 chars]',
    }, {
      source: { id: 'reuters', name: 'Reuters' }, author: 'Reuters Editorial', title: 'Protests sweep Lebanon for a second day', description: 'Protesters across Lebanon blocked roads with burning tires on Friday and marched in Beirut for a second day in demonstrations targeting the government over an economic crisis.', url: 'http://feeds.reuters.com/~r/reuters/topNews/~3/IBDl4F9Gagg/protests-sweep-lebanon-for-a-second-day-idUSKBN1WX0Q8', urlToImage: 'https://s4.reutersmedia.net/resources/r/?m=02&d=20191018&t=2&i=1442201111&w=1200&r=LYNXMPEF9H0JY', publishedAt: '2019-10-18T08:48:04Z', content: 'BEIRUT (Reuters) - Protesters across Lebanon blocked roads with burning tires on Friday and marched in Beirut for a second day in demonstrations targeting the government over an economic crisis. \r\nIn Lebanon’s biggest protest in years, thousands of people gat… [+3454 chars]',
    }, {
      source: { id: 'reuters', name: 'Reuters' }, author: 'Mert Ozkan', title: 'Shelling heard around Syrian town after Turkish-U.S. ceasefire deal', description: 'Shelling and gunfire resounded around the northeast Syrian town of Ras al Ain on Friday, a day after Turkey agreed with the United States to pause its offensive in Syria for five days to let Kurdish forces withdraw.', url: 'http://feeds.reuters.com/~r/reuters/topNews/~3/aFAbBC-pUXE/shelling-heard-around-syrian-town-after-turkish-u-s-ceasefire-deal-idUSKBN1WX0GT', urlToImage: 'https://s4.reutersmedia.net/resources_v2/images/rcom-default.png', publishedAt: '2019-10-18T08:27:00Z', content: 'CEYLANPINAR, Turkey (Reuters) - Shelling and gunfire resounded around the northeast Syrian town of Ras al Ain on Friday, a day after Turkey agreed with the United States to pause its offensive in Syria for five days to let Kurdish forces withdraw. \r\nMachine-g… [+5361 chars]',
    }],
  },
};
